Rudy/README.md
Submitting isPalindrome Attempt
=> first commit

Elisa/readme.md
=> Elisa Levet

Luxmi/README.md, Luxmi/backspace_string_compare.py, Luxmi/longest_substring.py, Luxmi/valid_palidrome.py
-- Question #1 Google Interview Question Two Sum (Easy)
-- Question #2 Container With Most Water (Medium)
-- *** Question #3 Trapping Rainwater (Hard) ***
-- Question #4 Backspace String Compare (Easy)
-- Question #5 Longest Substring Without Repeating Characters (Medium)
-- Question #6a Valid Palindrome(Easy)
-- Question #6b Valid Palindrome - 2
=> Day 1 assignment sans Trapping water problem - Luxmi Saha

Crispina/README.md
=> Crispina Muriel 03/01/2021 Homework

christopherLinares/README.md
Added christopherLinares folder and a README
=> twoSum using hash table

Aram/README.md
Functions pass by value NOT reference
var declarations are global/code reliant on globally scoped variables can be error prone if those variables are reused
let declarations are block scoped/ variables declared using let can be updated but not reassigned; if the same variable is defined in difference scopes, there will be no errors
const declarations are block scoped and maintain constant values, meaning they cannot be updated or reassigned within its scope
=> FIX: memo --to-- hash

Maria/README.md, Maria/TwoSum.js, Maria/ValidPalindrome.js
Trying to catch up...
> Completed Two Sum and Valid Palindrome
*** These are just my own solutions, I haven't viewed the walk through solutions on the Udemy Course yet. I wanted to try a couple myself first and then go back to optimize. Hope that is okay to do.
=> Completed 2 problems

Elisa/readme.md, Elisa/readmeCleanCode.md
finished first homework (just one problem was missing)
Getting some work done from Clean code
=> clean code progress

Crispina/CC.md, Crispina/README.md, Crispina/UDEMY.md
Going to have to catch up tomorrow
=> LinkedList problem 7 only

NickB/clean-code.md, NickB/readme.md
I wasn't able to complete all the problems will continue tomorrow, but still wanted to put a pr.
=> clean code problems (isnt complete)

Danny/README.md
Create my directory and README.md
=> Initial commit

Maria/README.md, Maria/ReverseList.js, Maria/TrappingRainwater.js
Updated README.md and added solutions for: 
1. Trapping Rainwater 
2. Reverse a linked list
=> 2 problems:Rainwater and reverse list

Elisa/readmeCleanCode.md, Elisa/readmeGrokking.md
Working on linked lists (my favorites)
added some more solutions to code clean ... I will be finishing everything by tomorrow
=> Work in progress

Groana/grokk/04_fastSlowPointers.js, Groana/masteringCode/01_twoNumSum.js, Groana/masteringCode/02_maxArea.js, Groana/masteringCode/03_trap.js, Groana/masteringCode/04_backspaceCompare.js, Groana/masteringCode/05_lengthOfLongestSubstring.js, Groana/masteringCode/06a_validPalindrome.js, Groana/masteringCode/06b_validPalindromeII.js, Groana/masteringCode/07_reverseLinkedList.js, Groana/masteringCode/readme.md
I'm not sure how to get rid of the floating files outside of my subfolders.
=> add: linked lists

Maria/README.md
Completed Linked List Cycle Problem from Grokking using fast and slow pointers. 
p.s. I'm not sure if it's okay to be making pull requests frequently or if I should wait until I complete several problems and make a PR at once.
=> Added:LL cycle problem

Crispina/README.md
Hi Abraham. I was really struggling with Link Lists but I was able to understand how to reverse a singly linked list now. I'm still struggling with the second LL question but I will watch the videos associated with them this morning. I hope to make another PR, or add on to this one, before class. See you soon.
=> re-try on LL question #1

Maria/ContainerWithMostWater.js, Maria/README.md, Maria/TwoSum.js, Maria/TwoSum_sorted.js
- backspace string compare 
- container with most water
- Two sum without sorting the array
=> PR for string problems

Crispina/BF.md, Crispina/CC.md, Crispina/README.md
Working on Clean code problems now
=> Four Clean Code solutions

Veronica/.gitignore, Veronica/CleanCode.md, Veronica/LinkedList.js, Veronica/Udemy.md
feat: added table of contents, secret file and gitignore experiment; finished Merge Doubly Linked List, Valid Parentheses, Implement Queue with Stacks, fixed and added comments on previous problems
=> More questions finished and secret

christopherLinares/CCH.md, christopherLinares/GTCI.md, christopherLinares/MTCI.md
Added three sliding window problems from Grokking
=> GTCI: Sliding Window

Maria/FruitsIntoBaskets.js, Maria/LongestSubstring.js, Maria/MaxSumSubArray.js, Maria/NonRepeatSubstring.js, Maria/README.md
PR for Sliding window problems
1. Max sum subarray of size k
2. smallest subarray given sum
3. fruits into baskets 
4. longest substring with k distinct characters
=> Sliding Window Problems

Veronica/Grokking.md
feat: added Sliding Window Problems to Grokking.md
=> feat: added Sliding Window Problems to Grokking.md

Crispina/assessment-1/problem-1.js, Crispina/patterns/linked_list_reversal.md, Crispina/patterns/sliding_window.md, Crispina/patterns/two_pointer.md
Hello Abe, 
Going slow, but still going! Thank you for all your feedback and hard work.
=> Add 2 patterns and assessment pseudo code

Maria/BinarySearch.md, Maria/SlidingWindow.md, Maria/SlidingWindow/MaxSubArray.js, Maria/TreeBFS.md, Maria/TreeDFS.md
**Modified:**
- SlidingWindow.md
**Added:**
- BinarySearch.md
- MaxSubarray.js 
- TreeBFS.md 
- TreeDFS.md
=> PR for trees hw 
